### ISSUE TITLE
支持AppleTV平台吗

### ISSUE THREAD

**Issue by huangxianhui001** [topameng/tolua_runtime#2]
感谢您的贡献!我们的游戏使用了你的库,运行在了iOS平台上.我们想要把我们的游戏移植到AppleTV平台上.想将支持iOS的.a库修改为支持tvOS的.但是遇到了一些问题,下面是的的移植过程:
1.下载你的仓库源码,然后打开了里面iOS文件夹里的工程,
2.修改了一些编译配置,如Supported Platforms改为tvOS,BaseSDK改为latest tvOS10.1,都是使用真机环境的,编译
3.然后将编译出来的.a库添加我的AppleTV工程中.我的TV工程也是从Unity中导出来的.已经做了一些修改,目前可以正常的运行在TV真机上,
但是将.a库添加到工程中编译时报了一堆错误,如
![snip20170104_2](https://cloud.githubusercontent.com/assets/10227237/21631212/a9deadd2-d273-11e6-96b2-b71df1cccb3b.png)
![snip20170104_1](https://cloud.githubusercontent.com/assets/10227237/21631214/b0e9e646-d273-11e6-81ab-d4b518ab6345.png)
提示的是一大堆符号找不到,不知是我编译出.a库的问题,还是本身这个tolua不支持tvOS平台?期待您的解答

**Comment by topameng** [comment]
没有Build过，也没有makefile文件，感觉luajit.a 需要重新编译
