### ISSUE TITLE
为什么tolua不能在Xcode模拟器上运行啊

### ISSUE THREAD

**Issue by youdk** [topameng/tolua_runtime#27]
我的Unity工程中使用了tolua框架，导出到xcode后，需要模拟器运行，但会报错：
dyld: Symbol not found: _luaL_newstate

我试了使用tolua Example里的Helloworld，导出后也报同样的错。

有人提到过这个问题，但我不太理解，也不清楚该怎么做。是否有支持模拟器的编译好了的库文件可以使用？
https://github.com/topameng/tolua_runtime/pull/11/commits/741df5ee02b9e377590aba10d4fdc2a583003d88

谢谢

**Comment by topameng** [comment]
不太需要，ios 模拟器不像安卓模拟器跟真机完全不一样，没有太多必要。如果想搞另行build吧
