### ISSUE TITLE
IOS XCODE 中报_luaopen_protobuf_c错误

### ISSUE THREAD

**Issue by YiDianerer** [topameng/tolua_runtime#7]
Undefined symbols for architecture arm64:
  "_luaopen_protobuf_c", referenced from:
      _LuaDLL_luaopen_protobuf_c_m3150460142 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _LuaDLL_luaopen_protobuf_c_m3150460142)
  "_luaopen_sproto_core", referenced from:
      _LuaDLL_luaopen_sproto_core_m2147190326 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _LuaDLL_luaopen_sproto_core_m2147190326)
ld: symbol(s) not found for architecture arm64

**Comment by topameng** [comment]
tolua_runtime 里面并没有pbc
